include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    argument_type_not_assignable: ignore
    avoid_dynamic_calls: ignore
    parameter_assignments: ignore
    comment_references: ignore
    avoid_catches_without_on_clauses: ignore
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    avoid_print: ignore
    avoid_redundant_argument_values: ignore
    unnecessary_getters_setters: ignore
